name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Получение исходников
        uses: actions/checkout@v1
      
      # Блеск и нищета NPM - очень часто авторы пакетов не следят за DEPRECATED
      - name: Настройка окружения Node-JS
        uses: actions/setup-node@v2
        with:
            node-version: '14.8.0'

      - name: 'change version'
        uses: reedyuk/npm-version@1.0.2
        with:
          version: '7.6.0'
      
      - name: Установка пакетов
        run: npm install
        

      # Штатный GH-Pages ломает сборку
      - name: Сборка сайта и развертывание
        run: npm deploy
      
      - name: Очистка CDN кеша
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Зона для очистки кеша и секретный токен для Github
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
